name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Build on multiple systems: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        config: [release, debug]

        include:
          - config: release
            cpp_flags: -O3
          - config: debug
            cpp_flags: -g -O0 -D_DEBUG

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Boost 1.75.0
      run: brew install boost

    - name: Install cmake
      run: brew install cmake

   - name: Get GCC 12 
      run: brew install gcc@12

    - name: CMake configure for Clang 14
      run: cmake -S . -B build
    
    - name: Compile with Clang
      run: cmake --build build

    - name: Run tests
      run: cmake --build build --target tests

    - name: CMake configure for GCC 12
      run: cmake -S . -B buildgcc -D CMAKE_C_COMPILER=gcc-12 -D CMAKE_CXX_COMPILER=g++-12
    
    - name: Compile with GCC
      run: cmake --build buildgcc

    - name: Run tests
      run: cmake --build buildgcc --target tests