name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Build on multiple systems: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang, gcc]
        config: [release, debug]

    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Boost
      run: brew install boost

    - name: CMake configure
      if: matrix.compiler == 'clang' && matrix.config == 'debug'
      run: cmake -S . -B build

    - name: CMake configure
      if: matrix.compiler == 'clang' && matrix.config == 'release'
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release

    - name: CMake configure
      if: matrix.compiler == 'gcc' && matrix.config == 'debug'
      run: cmake -S . -B build -D CMAKE_C_COMPILER=gcc-12 -D CMAKE_CXX_COMPILER=g++-12
            
    - name: CMake configure
      if: matrix.compiler == 'gcc' && matrix.config == 'release'
      run: cmake -S . -B build -D CMAKE_C_COMPILER=gcc-12 -D CMAKE_CXX_COMPILER=g++-12 -D CMAKE_BUILD_TYPE=Release

    - name: Compile
      run: cmake --build build

    - name: Run
      run: cmake --build build --target test
