name: ubuntu-20.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [release, debug]

        include:
          - config: release
            cpp_flags: -O3
          - config: debug
            cpp_flags: -g -O0 -D_DEBUG

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install GCC 12
        uses: egor-tensin/setup-gcc@v1
        with: 
            version: 12
            
      - name: get boost library
        run: sudo apt-get install libboost-dev

      - name: compile example
        run: gcc-12++ range.example.cpp -std=c++2b ${{matrix.cpp_flags}} -o example -v

      - name: run example
        run: ./example
